### ISSUE TITLE
Long repo name

### ISSUE THREAD

**Issue by mzarchi** [alirezafazeli8/learning-python-book#1]
The name of this repo is very long and it creates problems for developers, I think you should choose a shorter name like **python-book** to make it easier to work with in some cases.

**Comment by alirezafazeli8** [comment]
Hi mr zarchi , do you have another suggest name ?

**Comment by mzarchi** [comment]
- python-learning
- python-book
- python-course
- python-study
and ...

**Comment by alirezafazeli8** [comment]
Thanks, in a soon I change the name
